server:
    PORT: 5001
    NODE_ENV: development
    HOST: localhost
database:
    URL: mongodb+srv://nil:nil@cluster0.bxm5l.mongodb.net/
auth:
    JWKS_URI: http://localhost:9001/.well-known/jwks.json
